#### Concatenating all the hotels data of various cities

In [14]:
import pandas as pd
import numpy as np

In [15]:
data1=pd.read_csv("Hyderabad.csv")

In [16]:
data2=pd.read_csv("Bangalore.csv")

In [17]:
data3=pd.read_csv(r"C:\Users\yuges\Mumbai.csv")

In [18]:
data4=pd.read_csv(r"C:\Users\yuges\Chennai.csv")

In [19]:
data5=pd.read_csv(r"C:\Users\yuges\Kochi.csv")

In [20]:
data6=pd.read_csv(r"C:\Users\yuges\Pune.csv")

In [21]:
data7=pd.read_csv(r"C:\Users\yuges\Kolkata.csv")

In [22]:
data8=pd.read_csv(r"C:\Users\yuges\New Delhi.csv")

In [23]:
data9=pd.read_csv(r"C:\Users\yuges\Lucknow.csv")

In [24]:
data10=pd.read_csv(r"C:\Users\yuges\Noida.csv")

In [25]:
data=pd.concat([data1,data2,data3,data4,data5,data6,data7,data8,data9,data10],axis=0)

In [26]:
data

,Hotel Name,City,Distance from Centre (in km),Review (in words),Number of Reviews,Rating (out of 10),Level of sustainability,Type of Room,Type of Bed,Type of Cancellation,Cost,Taxes and charges,Type of Payment
0,FabExpress Golden Gate,Hyderabad,6.5 km,Good,82 reviews,7.9,Level 1,Deluxe Room,1 double bed,Free cancellation,"₹ 1,489",₹ 179,NaN
1,Collection O Orange Tree Hotels Near DLF,Hyderabad,9.3 km,NaN,NaN,NaN,NaN,Classic Triple Room,1 large double bed,Free cancellation,"₹ 2,393",₹ 303,No prepayment needed
2,Collection O 81504 Hotel Pride,Hyderabad,3.5 km,NaN,NaN,NaN,NaN,Classic Triple Room,1 large double bed,Free cancellation,"₹ 1,476",₹ 193,No prepayment needed
3,ibis Hyderabad Hitec City - An Accor Brand,Hyderabad,7.2 km,Good,"1,763 reviews",7.2,Level 3,Standard Queen Room,1 double bed,Free cancellation,"₹ 3,999",₹ 480,No prepayment needed
4,Avana- A Boutique Hotel,Hyderabad,11.6 km,Good,164 reviews,7.3,Level 3,Economy Double Room,1 extra-large double bed,NaN,"₹ 4,050",₹ 486,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FabHotel Culture,Noida,5.6 km,Review score,16 reviews,6.9,Level 1,Deluxe Room,1 double bed,Free cancellation,"₹ 1,320",₹ 158,NaN
96,FabExpress F9 Noida Sector 27,Noida,7.5 km,Good,40 reviews,7.2,Level 1,Deluxe Room,1 double bed,Free cancellation,"₹ 1,980",₹ 238,NaN
97,FabHotel F9 Sector 19,Noida,7.8 km,Good,43 reviews,7.7,Level 3,Deluxe Room,1 double bed,Free cancellation,"₹ 1,870",₹ 254,NaN
98,FabExpress Ashray,Noida,4.7 km,Good,32 reviews,7.9,Level 1,Deluxe Room,1 double bed,Free cancellation,"₹ 1,540",₹ 185,NaN
99,Itsy By Treebo - City Centre Noida,Noida,5.8 km,Review score,34 reviews,4.6,NaN,Economy Double Room,1 extra-large double bed,Free cancellation,"₹ 1,247",₹ 150,NaN

In [27]:
data.isna().sum() #Checking for missing values

Hotel Name                        0
City                              0
Distance from Centre (in km)      0
Review (in words)                68
Number of Reviews                68
Rating (out of 10)               69
Level of sustainability         421
Type of Room                      0
Type of Bed                       3
Type of Cancellation            128
Cost                              0
Taxes and charges                 9
Type of Payment                 402
dtype: int64

In [28]:
data["Review (in words)"].replace(np.nan,"No Review",inplace=True) #Replacing the missing values with No Review

In [29]:
data["Review (in words)"].isna().sum()

0

In [30]:
data["Number of Reviews"].replace(np.nan,0,inplace=True) #Filling the missing values in Number of Reviews column with 0

In [31]:
data["Number of Reviews"].isna().sum()

0

In [32]:
data["Rating (out of 10)"].replace(np.nan,0.0,inplace=True) #Filling the missing values in Rating column with 0.0

In [33]:
data["Rating (out of 10)"].isna().sum()

0

In [34]:
data.isna().sum()

Hotel Name                        0
City                              0
Distance from Centre (in km)      0
Review (in words)                 0
Number of Reviews                 0
Rating (out of 10)                0
Level of sustainability         421
Type of Room                      0
Type of Bed                       3
Type of Cancellation            128
Cost                              0
Taxes and charges                 9
Type of Payment                 402
dtype: int64

In [35]:
data["Level of sustainability"].replace(np.nan,0,inplace=True) #Replacing missing values in Level of sustainability column with 0

In [36]:
data["Level of sustainability"].isna().sum()

0

In [37]:
data["Type of Cancellation"].replace(np.nan,"Not Free",inplace=True) #Missing values are filled with Not Free in Type of Cancellation column

In [38]:
data["Type of Cancellation"].isna().sum()

0

In [39]:
data["Taxes and charges"].replace(np.nan,0,inplace=True) #Replacing missing values with 0

In [40]:
data["Taxes and charges"].isna().sum()

0

In [41]:
data["Type of Payment"].replace(np.nan,"prepayment",inplace=True) #Replacing missing values with prepayment

In [42]:
data["Type of Payment"].isna().sum()

0

In [43]:
data["Type of Bed"].fillna(data["Type of Bed"].mode()[0],inplace=True) #Filling missing values with mode because of categorical data

In [44]:
data.isna().sum() #All missing values are filled

Hotel Name                      0
City                            0
Distance from Centre (in km)    0
Review (in words)               0
Number of Reviews               0
Rating (out of 10)              0
Level of sustainability         0
Type of Room                    0
Type of Bed                     0
Type of Cancellation            0
Cost                            0
Taxes and charges               0
Type of Payment                 0
dtype: int64

In [45]:
data

,Hotel Name,City,Distance from Centre (in km),Review (in words),Number of Reviews,Rating (out of 10),Level of sustainability,Type of Room,Type of Bed,Type of Cancellation,Cost,Taxes and charges,Type of Payment
0,FabExpress Golden Gate,Hyderabad,6.5 km,Good,82 reviews,7.9,Level 1,Deluxe Room,1 double bed,Free cancellation,"₹ 1,489",₹ 179,prepayment
1,Collection O Orange Tree Hotels Near DLF,Hyderabad,9.3 km,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,"₹ 2,393",₹ 303,No prepayment needed
2,Collection O 81504 Hotel Pride,Hyderabad,3.5 km,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,"₹ 1,476",₹ 193,No prepayment needed
3,ibis Hyderabad Hitec City - An Accor Brand,Hyderabad,7.2 km,Good,"1,763 reviews",7.2,Level 3,Standard Queen Room,1 double bed,Free cancellation,"₹ 3,999",₹ 480,No prepayment needed
4,Avana- A Boutique Hotel,Hyderabad,11.6 km,Good,164 reviews,7.3,Level 3,Economy Double Room,1 extra-large double bed,Not Free,"₹ 4,050",₹ 486,prepayment
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FabHotel Culture,Noida,5.6 km,Review score,16 reviews,6.9,Level 1,Deluxe Room,1 double bed,Free cancellation,"₹ 1,320",₹ 158,prepayment
96,FabExpress F9 Noida Sector 27,Noida,7.5 km,Good,40 reviews,7.2,Level 1,Deluxe Room,1 double bed,Free cancellation,"₹ 1,980",₹ 238,prepayment
97,FabHotel F9 Sector 19,Noida,7.8 km,Good,43 reviews,7.7,Level 3,Deluxe Room,1 double bed,Free cancellation,"₹ 1,870",₹ 254,prepayment
98,FabExpress Ashray,Noida,4.7 km,Good,32 reviews,7.9,Level 1,Deluxe Room,1 double bed,Free cancellation,"₹ 1,540",₹ 185,prepayment
99,Itsy By Treebo - City Centre Noida,Noida,5.8 km,Review score,34 reviews,4.6,0,Economy Double Room,1 extra-large double bed,Free cancellation,"₹ 1,247",₹ 150,prepayment

In [46]:
data["Cost"]=data["Cost"].replace("₹|,","",regex=True) #Removing special characters in Cost column

In [47]:
data["Taxes and charges"]=data["Taxes and charges"].replace("₹|,","",regex=True) #Removing special characters

In [48]:
data

,Hotel Name,City,Distance from Centre (in km),Review (in words),Number of Reviews,Rating (out of 10),Level of sustainability,Type of Room,Type of Bed,Type of Cancellation,Cost,Taxes and charges,Type of Payment
0,FabExpress Golden Gate,Hyderabad,6.5 km,Good,82 reviews,7.9,Level 1,Deluxe Room,1 double bed,Free cancellation,1489,179,prepayment
1,Collection O Orange Tree Hotels Near DLF,Hyderabad,9.3 km,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,2393,303,No prepayment needed
2,Collection O 81504 Hotel Pride,Hyderabad,3.5 km,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,1476,193,No prepayment needed
3,ibis Hyderabad Hitec City - An Accor Brand,Hyderabad,7.2 km,Good,"1,763 reviews",7.2,Level 3,Standard Queen Room,1 double bed,Free cancellation,3999,480,No prepayment needed
4,Avana- A Boutique Hotel,Hyderabad,11.6 km,Good,164 reviews,7.3,Level 3,Economy Double Room,1 extra-large double bed,Not Free,4050,486,prepayment
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FabHotel Culture,Noida,5.6 km,Review score,16 reviews,6.9,Level 1,Deluxe Room,1 double bed,Free cancellation,1320,158,prepayment
96,FabExpress F9 Noida Sector 27,Noida,7.5 km,Good,40 reviews,7.2,Level 1,Deluxe Room,1 double bed,Free cancellation,1980,238,prepayment
97,FabHotel F9 Sector 19,Noida,7.8 km,Good,43 reviews,7.7,Level 3,Deluxe Room,1 double bed,Free cancellation,1870,254,prepayment
98,FabExpress Ashray,Noida,4.7 km,Good,32 reviews,7.9,Level 1,Deluxe Room,1 double bed,Free cancellation,1540,185,prepayment
99,Itsy By Treebo - City Centre Noida,Noida,5.8 km,Review score,34 reviews,4.6,0,Economy Double Room,1 extra-large double bed,Free cancellation,1247,150,prepayment

In [49]:
data["Number of Reviews"]=data["Number of Reviews"].replace(",|review|reviews|external|s","",regex=True) #Removing review,reviews and ,

In [50]:
data

,Hotel Name,City,Distance from Centre (in km),Review (in words),Number of Reviews,Rating (out of 10),Level of sustainability,Type of Room,Type of Bed,Type of Cancellation,Cost,Taxes and charges,Type of Payment
0,FabExpress Golden Gate,Hyderabad,6.5 km,Good,82,7.9,Level 1,Deluxe Room,1 double bed,Free cancellation,1489,179,prepayment
1,Collection O Orange Tree Hotels Near DLF,Hyderabad,9.3 km,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,2393,303,No prepayment needed
2,Collection O 81504 Hotel Pride,Hyderabad,3.5 km,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,1476,193,No prepayment needed
3,ibis Hyderabad Hitec City - An Accor Brand,Hyderabad,7.2 km,Good,1763,7.2,Level 3,Standard Queen Room,1 double bed,Free cancellation,3999,480,No prepayment needed
4,Avana- A Boutique Hotel,Hyderabad,11.6 km,Good,164,7.3,Level 3,Economy Double Room,1 extra-large double bed,Not Free,4050,486,prepayment
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FabHotel Culture,Noida,5.6 km,Review score,16,6.9,Level 1,Deluxe Room,1 double bed,Free cancellation,1320,158,prepayment
96,FabExpress F9 Noida Sector 27,Noida,7.5 km,Good,40,7.2,Level 1,Deluxe Room,1 double bed,Free cancellation,1980,238,prepayment
97,FabHotel F9 Sector 19,Noida,7.8 km,Good,43,7.7,Level 3,Deluxe Room,1 double bed,Free cancellation,1870,254,prepayment
98,FabExpress Ashray,Noida,4.7 km,Good,32,7.9,Level 1,Deluxe Room,1 double bed,Free cancellation,1540,185,prepayment
99,Itsy By Treebo - City Centre Noida,Noida,5.8 km,Review score,34,4.6,0,Economy Double Room,1 extra-large double bed,Free cancellation,1247,150,prepayment

In [51]:
data["Level of sustainability"]=data["Level of sustainability"].replace("Level| ","",regex=True)

In [52]:
data

,Hotel Name,City,Distance from Centre (in km),Review (in words),Number of Reviews,Rating (out of 10),Level of sustainability,Type of Room,Type of Bed,Type of Cancellation,Cost,Taxes and charges,Type of Payment
0,FabExpress Golden Gate,Hyderabad,6.5 km,Good,82,7.9,1,Deluxe Room,1 double bed,Free cancellation,1489,179,prepayment
1,Collection O Orange Tree Hotels Near DLF,Hyderabad,9.3 km,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,2393,303,No prepayment needed
2,Collection O 81504 Hotel Pride,Hyderabad,3.5 km,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,1476,193,No prepayment needed
3,ibis Hyderabad Hitec City - An Accor Brand,Hyderabad,7.2 km,Good,1763,7.2,3,Standard Queen Room,1 double bed,Free cancellation,3999,480,No prepayment needed
4,Avana- A Boutique Hotel,Hyderabad,11.6 km,Good,164,7.3,3,Economy Double Room,1 extra-large double bed,Not Free,4050,486,prepayment
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FabHotel Culture,Noida,5.6 km,Review score,16,6.9,1,Deluxe Room,1 double bed,Free cancellation,1320,158,prepayment
96,FabExpress F9 Noida Sector 27,Noida,7.5 km,Good,40,7.2,1,Deluxe Room,1 double bed,Free cancellation,1980,238,prepayment
97,FabHotel F9 Sector 19,Noida,7.8 km,Good,43,7.7,3,Deluxe Room,1 double bed,Free cancellation,1870,254,prepayment
98,FabExpress Ashray,Noida,4.7 km,Good,32,7.9,1,Deluxe Room,1 double bed,Free cancellation,1540,185,prepayment
99,Itsy By Treebo - City Centre Noida,Noida,5.8 km,Review score,34,4.6,0,Economy Double Room,1 extra-large double bed,Free cancellation,1247,150,prepayment

In [53]:
data["Distance from Centre (in km)"]=data["Distance from Centre (in km)"].replace("km","",regex=True)

In [54]:
data

,Hotel Name,City,Distance from Centre (in km),Review (in words),Number of Reviews,Rating (out of 10),Level of sustainability,Type of Room,Type of Bed,Type of Cancellation,Cost,Taxes and charges,Type of Payment
0,FabExpress Golden Gate,Hyderabad,6.5,Good,82,7.9,1,Deluxe Room,1 double bed,Free cancellation,1489,179,prepayment
1,Collection O Orange Tree Hotels Near DLF,Hyderabad,9.3,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,2393,303,No prepayment needed
2,Collection O 81504 Hotel Pride,Hyderabad,3.5,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,1476,193,No prepayment needed
3,ibis Hyderabad Hitec City - An Accor Brand,Hyderabad,7.2,Good,1763,7.2,3,Standard Queen Room,1 double bed,Free cancellation,3999,480,No prepayment needed
4,Avana- A Boutique Hotel,Hyderabad,11.6,Good,164,7.3,3,Economy Double Room,1 extra-large double bed,Not Free,4050,486,prepayment
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FabHotel Culture,Noida,5.6,Review score,16,6.9,1,Deluxe Room,1 double bed,Free cancellation,1320,158,prepayment
96,FabExpress F9 Noida Sector 27,Noida,7.5,Good,40,7.2,1,Deluxe Room,1 double bed,Free cancellation,1980,238,prepayment
97,FabHotel F9 Sector 19,Noida,7.8,Good,43,7.7,3,Deluxe Room,1 double bed,Free cancellation,1870,254,prepayment
98,FabExpress Ashray,Noida,4.7,Good,32,7.9,1,Deluxe Room,1 double bed,Free cancellation,1540,185,prepayment
99,Itsy By Treebo - City Centre Noida,Noida,5.8,Review score,34,4.6,0,Economy Double Room,1 extra-large double bed,Free cancellation,1247,150,prepayment

### Checking for duplicates

In [55]:
data.duplicated().sum() #To check the duplicates

1

In [56]:
data.drop_duplicates(inplace=True) #Removing duplicates

In [57]:
data.duplicated().sum()

0

### Datatype Conversion

In [58]:
data

,Hotel Name,City,Distance from Centre (in km),Review (in words),Number of Reviews,Rating (out of 10),Level of sustainability,Type of Room,Type of Bed,Type of Cancellation,Cost,Taxes and charges,Type of Payment
0,FabExpress Golden Gate,Hyderabad,6.5,Good,82,7.9,1,Deluxe Room,1 double bed,Free cancellation,1489,179,prepayment
1,Collection O Orange Tree Hotels Near DLF,Hyderabad,9.3,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,2393,303,No prepayment needed
2,Collection O 81504 Hotel Pride,Hyderabad,3.5,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,1476,193,No prepayment needed
3,ibis Hyderabad Hitec City - An Accor Brand,Hyderabad,7.2,Good,1763,7.2,3,Standard Queen Room,1 double bed,Free cancellation,3999,480,No prepayment needed
4,Avana- A Boutique Hotel,Hyderabad,11.6,Good,164,7.3,3,Economy Double Room,1 extra-large double bed,Not Free,4050,486,prepayment
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FabHotel Culture,Noida,5.6,Review score,16,6.9,1,Deluxe Room,1 double bed,Free cancellation,1320,158,prepayment
96,FabExpress F9 Noida Sector 27,Noida,7.5,Good,40,7.2,1,Deluxe Room,1 double bed,Free cancellation,1980,238,prepayment
97,FabHotel F9 Sector 19,Noida,7.8,Good,43,7.7,3,Deluxe Room,1 double bed,Free cancellation,1870,254,prepayment
98,FabExpress Ashray,Noida,4.7,Good,32,7.9,1,Deluxe Room,1 double bed,Free cancellation,1540,185,prepayment
99,Itsy By Treebo - City Centre Noida,Noida,5.8,Review score,34,4.6,0,Economy Double Room,1 extra-large double bed,Free cancellation,1247,150,prepayment

In [59]:
data.dtypes #Checking the datatype for each column

Hotel Name                       object
City                             object
Distance from Centre (in km)     object
Review (in words)                object
Number of Reviews                object
Rating (out of 10)              float64
Level of sustainability          object
Type of Room                     object
Type of Bed                      object
Type of Cancellation             object
Cost                             object
Taxes and charges                object
Type of Payment                  object
dtype: object

In [60]:
data["Distance from Centre (in km)"].max()

'9.9 '

In [61]:
data["Distance from Centre (in km)"]=data["Distance from Centre (in km)"].astype("float32") #Changing the datatype from object to float

In [62]:
data.dtypes

Hotel Name                       object
City                             object
Distance from Centre (in km)    float32
Review (in words)                object
Number of Reviews                object
Rating (out of 10)              float64
Level of sustainability          object
Type of Room                     object
Type of Bed                      object
Type of Cancellation             object
Cost                             object
Taxes and charges                object
Type of Payment                  object
dtype: object

In [63]:
data["Number of Reviews"]=data["Number of Reviews"].astype("int16")

In [64]:
data.dtypes

Hotel Name                       object
City                             object
Distance from Centre (in km)    float32
Review (in words)                object
Number of Reviews                 int16
Rating (out of 10)              float64
Level of sustainability          object
Type of Room                     object
Type of Bed                      object
Type of Cancellation             object
Cost                             object
Taxes and charges                object
Type of Payment                  object
dtype: object

In [65]:
data["Rating (out of 10)"]=data["Rating (out of 10)"].astype("float32")

In [66]:
data["Level of sustainability"]=data["Level of sustainability"].astype("int8")

In [67]:
data["Cost"]=data["Cost"].astype("float16")

In [68]:
data["Taxes and charges"]=data["Taxes and charges"].astype("float16")

In [69]:
data

,Hotel Name,City,Distance from Centre (in km),Review (in words),Number of Reviews,Rating (out of 10),Level of sustainability,Type of Room,Type of Bed,Type of Cancellation,Cost,Taxes and charges,Type of Payment
0,FabExpress Golden Gate,Hyderabad,6.5,Good,82,7.9,1,Deluxe Room,1 double bed,Free cancellation,1489.0,179.0,prepayment
1,Collection O Orange Tree Hotels Near DLF,Hyderabad,9.3,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,2392.0,303.0,No prepayment needed
2,Collection O 81504 Hotel Pride,Hyderabad,3.5,No Review,0,0.0,0,Classic Triple Room,1 large double bed,Free cancellation,1476.0,193.0,No prepayment needed
3,ibis Hyderabad Hitec City - An Accor Brand,Hyderabad,7.2,Good,1763,7.2,3,Standard Queen Room,1 double bed,Free cancellation,4000.0,480.0,No prepayment needed
4,Avana- A Boutique Hotel,Hyderabad,11.6,Good,164,7.3,3,Economy Double Room,1 extra-large double bed,Not Free,4050.0,486.0,prepayment
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FabHotel Culture,Noida,5.6,Review score,16,6.9,1,Deluxe Room,1 double bed,Free cancellation,1320.0,158.0,prepayment
96,FabExpress F9 Noida Sector 27,Noida,7.5,Good,40,7.2,1,Deluxe Room,1 double bed,Free cancellation,1980.0,238.0,prepayment
97,FabHotel F9 Sector 19,Noida,7.8,Good,43,7.7,3,Deluxe Room,1 double bed,Free cancellation,1870.0,254.0,prepayment
98,FabExpress Ashray,Noida,4.7,Good,32,7.9,1,Deluxe Room,1 double bed,Free cancellation,1540.0,185.0,prepayment
99,Itsy By Treebo - City Centre Noida,Noida,5.8,Review score,34,4.6,0,Economy Double Room,1 extra-large double bed,Free cancellation,1247.0,150.0,prepayment

In [70]:
data.dtypes

Hotel Name                       object
City                             object
Distance from Centre (in km)    float32
Review (in words)                object
Number of Reviews                 int16
Rating (out of 10)              float32
Level of sustainability            int8
Type of Room                     object
Type of Bed                      object
Type of Cancellation             object
Cost                            float16
Taxes and charges               float16
Type of Payment                  object
dtype: object

In [71]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1001 entries, 0 to 99
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Hotel Name                    1001 non-null   object
 1   City                          1001 non-null   object
 2   Distance from Centre (in km)  1001 non-null   float32
 3   Review (in words)             1001 non-null   object
 4   Number of Reviews             1001 non-null   int16
 5   Rating (out of 10)            1001 non-null   float32
 6   Level of sustainability       1001 non-null   int8
 7   Type of Room                  1001 non-null   object
 8   Type of Bed                   1001 non-null   object
 9   Type of Cancellation          1001 non-null   object
 10  Cost                          1001 non-null   float16
 11  Taxes and charges             1001 non-null   float16
 12  Type of Payment               1001 non-null   object
dtypes: float16(2), float32(2), int16(1), int8(1), object(7)
memory usage: 77.2+ KB

In [72]:
data.to_csv("Hotels.csv",index=None)